# Generated by Django 5.2.8 on 2025-12-12 06:01

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_logo_profile_bio_profile_location_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_requests', to='accounts.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(default=services.models.default_service, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.service'),
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
