# Generated by Django 5.2.8 on 2025-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceprovider_servicerequest_delete_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
