# Generated by Django 5.2.8 on 2025-12-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_bio_alter_user_location_serviceprovider'),
        ('services', '0003_serviceprovider_city_serviceprovider_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.serviceprovider'),
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
