# Generated by Django 5.2.8 on 2025-12-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='providers', to='services.service'),
        ),
    ]
