# Generated by Django 5.2.8 on 2025-12-12 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logo',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='users', to='services.service'),
        ),
    ]
