# Generated by Django 5.2.8 on 2025-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_bio_alter_user_location_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='providers', to='accounts.service'),
        ),
    ]
