# Generated by Django 5.2.8 on 2025-12-09 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_serviceprovider_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
